#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/database
- name: Run database container
  docker_container:
    name: tp1_database
    image: "sebdors/devops_tp-db:latest" 
    state: started
    restart_policy: unless-stopped
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "db"
      POSTGRES_USER: "usr"
      POSTGRES_PASSWORD: "pwd"