#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/api
- name: Run api container
  docker_container:
    name: tp1_api
    image: "sebdors/devops_tp-backend:latest"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: app-network
    env:
      DATABASE_HOST: "tp1_database"